//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSetAccessPoints.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataSetAccessPoints.xsd", IsNullable=false)]
public partial class DataSetAccessPoints {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Element", typeof(DataSetAccessPointsElement))]
    [System.Xml.Serialization.XmlElementAttribute("ProjectInfo", typeof(DataSetAccessPointsProjectInfo))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSetAccessPoints.xsd")]
public partial class DataSetAccessPointsElement {
    
    private string partIDField;
    
    private string manufacturerField;
    
    private string modelNumberField;
    
    private string mACAddressField;
    
    private string iPAddressField;
    
    private string bandField;
    
    private string technologyField;
    
    private string sSIDField;
    
    private string channelField;
    
    private string outputPowerField;
    
    private string floorNumberField;
    
    private string latitudeField;
    
    private string componentgroupField;
    
    private string groupFloorNumberField;
    
    private string azimuthField;
    
    private string heightField;
    
    private string longitudeField;
    
    private string uTMZoneField;
    
    private string partIDSortingField;
    
    private string uniqueIDField;
    
    private string imageFilenameField;
    
    private string planSortOrderField;
    
    private string powerPerChannelField;
    
    private string compositePowerField;
    
    private string rSCPRSRPField;
    
    private string orderNumberField;
    
    private string showOrderNumberField;
    
    private string serialNumField;
    
    /// <remarks/>
    public string PartID {
        get {
            return this.partIDField;
        }
        set {
            this.partIDField = value;
        }
    }
    
    /// <remarks/>
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string ModelNumber {
        get {
            return this.modelNumberField;
        }
        set {
            this.modelNumberField = value;
        }
    }
    
    /// <remarks/>
    public string MACAddress {
        get {
            return this.mACAddressField;
        }
        set {
            this.mACAddressField = value;
        }
    }
    
    /// <remarks/>
    public string IPAddress {
        get {
            return this.iPAddressField;
        }
        set {
            this.iPAddressField = value;
        }
    }
    
    /// <remarks/>
    public string Band {
        get {
            return this.bandField;
        }
        set {
            this.bandField = value;
        }
    }
    
    /// <remarks/>
    public string Technology {
        get {
            return this.technologyField;
        }
        set {
            this.technologyField = value;
        }
    }
    
    /// <remarks/>
    public string SSID {
        get {
            return this.sSIDField;
        }
        set {
            this.sSIDField = value;
        }
    }
    
    /// <remarks/>
    public string Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    public string OutputPower {
        get {
            return this.outputPowerField;
        }
        set {
            this.outputPowerField = value;
        }
    }
    
    /// <remarks/>
    public string FloorNumber {
        get {
            return this.floorNumberField;
        }
        set {
            this.floorNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public string Componentgroup {
        get {
            return this.componentgroupField;
        }
        set {
            this.componentgroupField = value;
        }
    }
    
    /// <remarks/>
    public string GroupFloorNumber {
        get {
            return this.groupFloorNumberField;
        }
        set {
            this.groupFloorNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Azimuth {
        get {
            return this.azimuthField;
        }
        set {
            this.azimuthField = value;
        }
    }
    
    /// <remarks/>
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public string Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public string UTMZone {
        get {
            return this.uTMZoneField;
        }
        set {
            this.uTMZoneField = value;
        }
    }
    
    /// <remarks/>
    public string PartIDSorting {
        get {
            return this.partIDSortingField;
        }
        set {
            this.partIDSortingField = value;
        }
    }
    
    /// <remarks/>
    public string UniqueID {
        get {
            return this.uniqueIDField;
        }
        set {
            this.uniqueIDField = value;
        }
    }
    
    /// <remarks/>
    public string ImageFilename {
        get {
            return this.imageFilenameField;
        }
        set {
            this.imageFilenameField = value;
        }
    }
    
    /// <remarks/>
    public string PlanSortOrder {
        get {
            return this.planSortOrderField;
        }
        set {
            this.planSortOrderField = value;
        }
    }
    
    /// <remarks/>
    public string PowerPerChannel {
        get {
            return this.powerPerChannelField;
        }
        set {
            this.powerPerChannelField = value;
        }
    }
    
    /// <remarks/>
    public string CompositePower {
        get {
            return this.compositePowerField;
        }
        set {
            this.compositePowerField = value;
        }
    }
    
    /// <remarks/>
    public string RSCPRSRP {
        get {
            return this.rSCPRSRPField;
        }
        set {
            this.rSCPRSRPField = value;
        }
    }
    
    /// <remarks/>
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ShowOrderNumber {
        get {
            return this.showOrderNumberField;
        }
        set {
            this.showOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    public string SerialNum {
        get {
            return this.serialNumField;
        }
        set {
            this.serialNumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSetAccessPoints.xsd")]
public partial class DataSetAccessPointsProjectInfo {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
