//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("Antennas Report", Namespace="", IsNullable=false)]
public partial class AntennasReport {
    
    private AntennasReportTable1[] table1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Table1")]
    public AntennasReportTable1[] Table1 {
        get {
            return this.table1Field;
        }
        set {
            this.table1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AntennasReportTable1 {
    
    private string tXTANTENNAEREPORTTITLEField;
    
    private string tEXT28Field;
    
    private string tXTANTMODELField;
    
    private string tXTPROJECTNAMEField;
    
    private string tEXT34Field;
    
    private string tXTSOURCEIDField;
    
    private string tXTDESIGNCOMPANYTITLEField;
    
    private string tXTANTGAINField;
    
    private string tXTDESIGNCOMPANYField;
    
    private string tXTTOTALLOSSGAINField;
    
    private string tXTPAGEField;
    
    private string tXTANTERPField;
    
    private string tEXT42Field;
    
    /// <remarks/>
    public string TXTANTENNAEREPORTTITLE {
        get {
            return this.tXTANTENNAEREPORTTITLEField;
        }
        set {
            this.tXTANTENNAEREPORTTITLEField = value;
        }
    }
    
    /// <remarks/>
    public string TEXT28 {
        get {
            return this.tEXT28Field;
        }
        set {
            this.tEXT28Field = value;
        }
    }
    
    /// <remarks/>
    public string TXTANTMODEL {
        get {
            return this.tXTANTMODELField;
        }
        set {
            this.tXTANTMODELField = value;
        }
    }
    
    /// <remarks/>
    public string TXTPROJECTNAME {
        get {
            return this.tXTPROJECTNAMEField;
        }
        set {
            this.tXTPROJECTNAMEField = value;
        }
    }
    
    /// <remarks/>
    public string TEXT34 {
        get {
            return this.tEXT34Field;
        }
        set {
            this.tEXT34Field = value;
        }
    }
    
    /// <remarks/>
    public string TXTSOURCEID {
        get {
            return this.tXTSOURCEIDField;
        }
        set {
            this.tXTSOURCEIDField = value;
        }
    }
    
    /// <remarks/>
    public string TXTDESIGNCOMPANYTITLE {
        get {
            return this.tXTDESIGNCOMPANYTITLEField;
        }
        set {
            this.tXTDESIGNCOMPANYTITLEField = value;
        }
    }
    
    /// <remarks/>
    public string TXTANTGAIN {
        get {
            return this.tXTANTGAINField;
        }
        set {
            this.tXTANTGAINField = value;
        }
    }
    
    /// <remarks/>
    public string TXTDESIGNCOMPANY {
        get {
            return this.tXTDESIGNCOMPANYField;
        }
        set {
            this.tXTDESIGNCOMPANYField = value;
        }
    }
    
    /// <remarks/>
    public string TXTTOTALLOSSGAIN {
        get {
            return this.tXTTOTALLOSSGAINField;
        }
        set {
            this.tXTTOTALLOSSGAINField = value;
        }
    }
    
    /// <remarks/>
    public string TXTPAGE {
        get {
            return this.tXTPAGEField;
        }
        set {
            this.tXTPAGEField = value;
        }
    }
    
    /// <remarks/>
    public string TXTANTERP {
        get {
            return this.tXTANTERPField;
        }
        set {
            this.tXTANTERPField = value;
        }
    }
    
    /// <remarks/>
    public string TEXT42 {
        get {
            return this.tEXT42Field;
        }
        set {
            this.tEXT42Field = value;
        }
    }
}
